### PR TITLE
Add summary action

### LINKED ISSUE #12: Produce copy&pasteable list of URLs to upladed PyPI packages
It would be great if the process of publishing packages produces copy & pasteable list of published packages.

When we upload using twine, twine provides such a list as output (but it's random order), and we use it to copy & paste it to the email sent. There is a comment "sort it before" because otherwise it's very difficult to find provider you are looking for on the list

You can see it in the last email where @eladkal did not sort it :) (and it's especially visible if you upload a big number of providers) https://lists.apache.org/thread/1jwvb6449qx91tf74how5jkm3jyrstjt

So the list of URLS should be nicely sorted and printed, possibly with some markers COPY FROM HERE  , COPY TO HERE

### PR DESCRIPTION
**Pull request by gopidesupavan**
To click and see the package:

image

To copy all the package names easily:

image

### CODE REVIEW

**Comment by gopidesupavan** [comment]
May be this can be extended for all the actions. basically to display what validations are passed and failed in job summary something like.

**Comment by potiuk** [comment]
> May be this can be extended for all the actions. basically to display what validations are passed and failed in job summary something like.

Great idea!

**Comment by potiuk** [comment]
We still have some 3 weeks until new .asf.yaml infrastructure will be released to be able to test the deployment environments, so we can definitely iterate and improve things :)

**Comment by gopidesupavan** [comment]
> We still have some 3 weeks until new .asf.yaml infrastructure will be released to be able to test the deployment environments, so we can definitely iterate and improve things :)

Yeah absolutely, will improve further futures and at last we can refactor documentation and add some images of validations and publish artifacts..

**Review by potiuk — APPROVED** [review]

**Pull request merged**
